vaadin.launch-browser=true
spring.application.name=famigo

spring.devtools.restart.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/famigo
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
vaadin.productionMode=false
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true