-- Baseline: Schema-Stand vor Einführung von Flyway (vorher von Hibernate ddl-auto=update erzeugt).
-- Bestehende Datenbanken überspringen diese Migration (baseline-on-migrate, baseline-version=1).

CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(255),
    password_hash varchar(255) NOT NULL,
    user_role     varchar(255) NOT NULL CHECK (user_role IN ('PARENT', 'CHILD')),
    stars         integer      NOT NULL,
    username      varchar(255) NOT NULL,
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
);

CREATE TABLE parent_child (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id  bigint NOT NULL REFERENCES users (id),
    parent_id bigint NOT NULL REFERENCES users (id)
);

CREATE TABLE task_templates (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  text,
    stars_reward integer NOT NULL,
    title        varchar(255)
);

CREATE TABLE tasks (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description    text,
    due_date       date,
    stars_reward   integer NOT NULL,
    status         varchar(255) CHECK (status IN ('PENDING', 'DONE', 'APPROVED')),
    title          varchar(255),
    assigned_to_id bigint REFERENCES users (id),
    created_by_id  bigint REFERENCES users (id),
    template_id    bigint REFERENCES task_templates (id)
);

CREATE TABLE reward (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description   text,
    redeemed      boolean NOT NULL,
    star_cost     integer NOT NULL,
    title         varchar(255),
    child_id      bigint  NOT NULL REFERENCES users (id),
    created_by_id bigint REFERENCES users (id),
    task_id       bigint REFERENCES tasks (id)
);

CREATE TABLE reward_option (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active       boolean NOT NULL,
    category     varchar(255) CHECK (category IN ('MATERIELL', 'ZEIT', 'ERLEBNIS', 'SELBSTWUNSCH', 'GELD', 'SPECIAL')),
    cost         integer NOT NULL,
    description  varchar(255),
    title        varchar(255),
    create_by_id bigint REFERENCES users (id)
);

CREATE TABLE child_reward_transaction (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    implemented     boolean NOT NULL,
    redeemed_at     timestamp(6),
    stars_spent     integer NOT NULL,
    viewed_by_child boolean NOT NULL,
    child_id        bigint REFERENCES users (id),
    reward_id       bigint REFERENCES reward_option (id)
);
